### ISSUE TITLE
Demo Domain is Dead, Here is a suggested replacement

### ISSUE THREAD

**Issue by TOGLK** [YunoHost-Apps/librex_ynh#18]
### Describe the bug

When trying to load the "Demo" for the "LibreX" Yuno Web Applet via the use of the "Demo" button I am sent to a dead domain that no longer hosts a "LibreX" instance and the domain is now up for sale.

### Context

- Hardware: N/A
- YunoHost version: N/A
- I have access to my server: N/A (Public Domain)
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: N/A
  - If yes, please explain: N/A
- Using, or trying to install package version/branch: N/A
- If upgrading, current package version: N/A

### Steps to reproduce

- Open up the Application Webpage for "LibreX"
- Click the green button at the top of the page labeled "Demo"
- Error reproduced successfully

### Expected behavior

The "Demo" button should open up to a usable webpage that functions as expected and offers full functionality of the application in question to the furthest extent possible without requiring input of any personally information or individual account information.

### Logs

N/A

### Suggested Fix

Replace the current domain with this domain or some other domain of the communities choosing.
Suggested replacement domain: https://librey.devol.it/

### Additional Notes

I'm not affiliated with the suggested domain, LibreX, YunoHost, or any other projected linked with YunoHost, LibreX, or the suggested replacement domain.
I'm not responsible for any decisions made as to what domain ends up being used.

Please do your own checks into whether the domain I found is a suitable replacement or not, I have no experience of LibreX or what it is meant to do, I only discovered it 1 hour ago.

**Comment by ericgaspar** [comment]
fixed
