### ISSUE TITLE
Cannot add search engine to browser because of right on opensearch xml file

### ISSUE THREAD

**Issue by guizmoau** [YunoHost-Apps/librex_ynh#2]
### Describe the bug

Cannot add search engine to browser because of right on opensearch xml file

### Context

- Hardware: VPS bought online
- YunoHost version: latest stable
- I have access to my server:  SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

### Steps to reproduce

install app
go in your favorite firefox
try to add search engine by navigating the homepage and click on add search engine button
error message on browser

### Expected behavior

after changing rights of the file in error message it works

**Comment by ericgaspar** [comment]
> after changing rights of the file in error message it works

what value did you used?
