### ISSUE TITLE
librex service restarts every 10 seconds

### ISSUE THREAD

**Issue by lost-geographer** [YunoHost-Apps/librex_ynh#4]
Interesting app btw, thanks for the packaging!

### Describe the bug

*The librex service restarts every 10 seconds. But this behaviour is not noticeable until you look into the logs…*
*It seems that there is a missing script that makes the service restart: /var/www/librex/auto_updater.sh*

### Context

- Hardware: *VPS bought online*
- YunoHost version: *11.1.5 (stable)*
- I have access to my server: *Through SSH & through the web-admin interface*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *No*
- Using package version: *20221217~ynh1*

### Steps to reproduce

- *Installation via the web-admin interface or the CLI*

### Expected behavior

*The librex service should not restart every 10 seconds.*

### Logs

Logs are here: https://paste.yunohost.org/igavivemiy

**Comment by FranzMari** [comment]
Hi,
As far as I can see, those files are not in the main upstream repo anymore. 
Stopping the systemd service has no impact on my Librex instance.
What about removing the librex.service file

**Comment by lost-geographer** [comment]
Ah, indeed, I linked an old commit :/

Removing the librex.service won't affect the Librex instance either. There is just Yunohost complaining that it fails to get information for the service, since it doesn't exist for systemd.

Probably the next update will solve the issue.

**Comment by ericgaspar** [comment]
I let you close the issue if this is fixed
